###
GET http://127.0.0.1:3003/api/book/20

###
GET http://127.0.0.1:3003/api/book/b72f94f2-bc09-49e4-85a6-83fd7eaa29c0

###
POST http://127.0.0.1:3003/api/book
Content-Type: application/json

{
"book": {
    "title": "Rayuela",
    "author": "Julio Cortázar",
    "isbn": "978-950-07-0000-0",
    "publishedDate": "1963-06-28",
    "availableCopies": 5
    }
}

###
POST http://127.0.0.1:3003/api/book
Content-Type: application/json

{
"book": {
    "title": "Prueba para Examen",
    "author": "Anderson ocaña",
    "isbn": "999-999-99-9999-9",
    "publishedDate": "2025-05-14",
    "availableCopies": 1
    }
}

//estoy haciendo el get primero, luego el put y luego el delete sobre el mismo libro!
//si se invierte el orden no va a andar jeje

###
PUT http://localhost:3003/api/book/b72f94f2-bc09-49e4-85a6-83fd7eaa29c0
Content-Type: application/json

{
  "title": "Cien años de soledad (Edición actualizada)",
  "author": "Gabriel García Márquez",
  "isbn": "978-3-16-148410-0",
  "publishedDate": "1967-06-05",
  "availableCopies": 6
}

###
DELETE http://127.0.0.1:3003/api/book/b72f94f2-bc09-49e4-85a6-83fd7eaa29c0
